extends SceneTree
func _initialize() -> void:
	var state = preload("res://scripts/world/fog_of_war_state.gd").new()
	state.configure(52)
	assert(not state.is_explored(Vector3.ZERO))
	state.update([{"position": Vector3.ZERO, "radius": 8, "feather": 4}])
	assert(state.is_visible(Vector3.ZERO) and state.is_explored(Vector3.ZERO))
	assert(state.sample(Vector3(10,0,0)) > 0 and state.sample(Vector3(10,0,0)) < 1)
	assert(not state.is_visible(Vector3(30,0,0)))
	var first: PackedByteArray = state.explored.duplicate()
	state.update([{"position": Vector3(30,0,0), "radius": 8, "feather": 4}])
	assert(not state.is_visible(Vector3.ZERO) and state.is_explored(Vector3.ZERO))
	assert(state.is_visible(Vector3(30,0,0)))
	for i in first.size(): assert(state.explored[i] >= first[i])
	state.update([{"position": Vector3(-48,0,-48), "radius": 8, "feather": 4}, {"position": Vector3(40,0,40), "radius": 6, "feather": 2}])
	assert(state.is_visible(Vector3(-48,0,-48)) and state.is_visible(Vector3(40,0,40)))
	assert(not state.is_visible(Vector3.INF) and not state.is_explored(Vector3(60,0,0)))
	state.update([])
	assert(not state.is_visible(Vector3(40,0,40)) and state.is_explored(Vector3(40,0,40)))
	state.configure(52)
	assert(not state.is_explored(Vector3(40,0,40)))
	print("FOG_STATE_PASS discovery memory sight multiple_sources border reset")
	quit()
